# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_auto_20180115_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='university',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
